### ISSUE TITLE
Add link to google play store

### ISSUE THREAD

**Issue by timkim** [phonegap/app.phonegap.com#28]
eom

**Comment by mwbrooks** [comment]
@timkim allow @jahoni to do this. The CSS class still needs to be updated and the text should not be underlined. She also has a specific wording in mind.

Additionally, the WP8 copy should be updated to "soon-ish" instead of later.

**Comment by timkim** [comment]
All right.

**Comment by jahoni** [comment]
k. done.

for future reference:
the class "main-btn" should be applied to the active store buttons, and the <span> should change to an <a>. the svg for each store logo also needs to be updated to change colour (from blue to white).

i didn't use "soon-ish" for the windows phone button because the text was too long and made the button wrap weird. so yeah.
